version: "2"
services:
  mysql-db:
    image: percona
    environment:
      - MYSQL_ROOT_PASSWORD=abcd1234
      - LANG=en_US.UTF-8
    ports:
      - 3306:3306
    volumes:
      - product_db_data:/var/lib/mysql

  nvdmirror:
    image: sspringett/nvdmirror
    ports:
      - 8380:80
    volumes:
      - ./.nvdmirror:/usr/local/apache2/htdocs

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.url=jdbc:postgresql://sonar-db:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

  sonar-db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  product_db_data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  postgresql:
  postgresql_data:
