spring:
  datasource:
    url: jdbc:mysql://dev-db-release-mysql.dev.svc.cluster.local:3306/product_database?characterEncoding=UTF-8&useSSL=false
    username: root
    password: gbHT4vamMd
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: "classpath:/db/migration"
