spring:
  datasource:
    url: jdbc:mysql://mysql-release:3306/example_db?characterEncoding=UTF-8&useSSL=false
    username: root
    password: b0JeSRgCTS
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: "classpath:/db/migration"
