spring:
  datasource:
    url: jdbc:mysql://mysql-0.mysql.svc.cluster.local:3306/example_db?characterEncoding=UTF-8&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: "classpath:/db/migration"
