spring:
  datasource:
    url: jdbc:mysql://product-dev-db-release-mysql.dev.svc.cluster.local:3307/product_database?characterEncoding=UTF-8&useSSL=false
    username: root
    password: Scm90s6kP3
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: "classpath:/db/migration"
